# Generated by Django 5.2 on 2025-05-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('hospitalAdmin', 'HospitalAdmin')], max_length=20)),
                ('hospitalId', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
