# Generated by Django 5.2 on 2025-05-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='severity_score',
        ),
        migrations.RemoveField(
            model_name='diseasecase',
            name='case_count',
        ),
        migrations.RemoveField(
            model_name='outbreak',
            name='end_date',
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='avg_7day_cases',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='daily_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='humidity_pct',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diseasecase',
            name='rain_mm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='diseasecase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='outbreak',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
