# Generated by Django 5.2 on 2025-05-05 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_disease_severity_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasecase',
            old_name='humidity_pct',
            new_name='humidity',
        ),
        migrations.RenameField(
            model_name='diseasecase',
            old_name='rain_mm',
            new_name='temperature',
        ),
    ]
