# Generated by Django 5.2 on 2025-06-27 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inventorynotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseResourceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_patient', models.PositiveIntegerField(default=1)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disease')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
